#name: github-action
name: cii
on: [push]
jobs:
  check-bats-version:
    runs-on: [self-hosted, ci]


    steps:
     # checkout
      - uses: actions/checkout@v2
      - run: uptime && sleep 5 && echo "salut"
