name: github-action
#name: ci
on: [push]
jobs:
  check-bats-version:
    runs-on: [self-hosted, ci]


    steps:
     # checkout
      - uses: actions/checkout@v2
      - run: uptime && sleep 10 && echo "salut"

      - run: chmod 777 script && ./script
        working-directory: ./
