name: github-action
#name: ci
on: [push]
jobs:
  check-bats-version:
    runs-on: [self-hosted, ci]


    steps:
     # checkout
      - uses: actions/checkout@v2
      - run: uptime && sleep 60 && echo "salut"
